// backend/controllers/timetableController.js
import { db } from '../config/firebase.js';
import Timetable from '../models/Timetable.js';
// import { generateTimetable } from '../services/timetableService.js'; // If you have complex generation logic

// Function to generate and save a timetable
const createTimetable = async (req, res) => {
  try {
    const { userId, rawData, syllabusPdfUrl, availability, startDate, studyTime } = req.body; // rawData could be text from AI agent or a reference to a PDF

    if (!userId || !rawData || !availability || !startDate || !studyTime) {
      return res.status(400).send({ message: "userId, rawData, availability, startDate, and studyTime are required." });
    }

    // In a real scenario, rawData would be processed by your AI agent
    // or further processed here to extract relevant information for timetable generation.
    // For demonstration, let's assume rawData is already processed into a schedule format.

    // Example: Generate a simple timetable (replace with actual AI agent output or complex logic)
    // In a real scenario, you would integrate with your AI agent here.
    // The AI agent would take rawData (text/PDF reference), availability, startDate, and studyTime
    // to generate a comprehensive timetable.
    const generatedTimetableData = {
      // Placeholder for AI agent generated timetable
      // This structure would be determined by the AI agent's output
      monday: "Math 9:00 AM - 10:00 AM (Study 2 hours)",
      tuesday: "Science 10:00 AM - 11:00 AM (Study 1 hour)",
      wednesday: "Break",
      // ... more schedule details generated by AI
      inputDetails: {
        rawData: rawData,
        syllabusPdfUrl: syllabusPdfUrl,
        availability: availability,
        startDate: startDate,
        studyTime: studyTime
      }
    };

    const newTimetable = new Timetable(userId, generatedTimetableData);
    const timetableRef = await db.collection('timetables').add(newTimetable.toFirestore());

    res.status(201).send({
      message: "Timetable created successfully",
      id: timetableRef.id,
      timetable: newTimetable.toFirestore()
    });
  } catch (error) {
    console.error("Error creating timetable:", error);
    res.status(500).send({ message: "Failed to create timetable", error: error.message });
  }
};

// Function to get a user's timetable
const getTimetable = async (req, res) => {
  try {
    const { userId } = req.params;

    if (!userId) {
      return res.status(400).send({ message: "userId is required." });
    }

    const snapshot = await db.collection('timetables').where('userId', '==', userId).get();

    if (snapshot.empty) {
      return res.status(404).send({ message: "No timetable found for this user." });
    }

    const timetables = [];
    snapshot.forEach(doc => {
      timetables.push({ id: doc.id, ...doc.data() });
    });

    res.status(200).send(timetables);
  } catch (error) {
    console.error("Error fetching timetable:", error);
    res.status(500).send({ message: "Failed to fetch timetable", error: error.message });
  }
};

export {
  createTimetable,
  getTimetable
};

